### ISSUE TITLE
add information about local neighbourhood policing teams to pins

### ISSUE THREAD

**Issue by ghost** [PoliceRewired/cvth-groups-map#1]
Information about the local policing neighbourhood team for most pins on the map is available through the [source data sheet](https://docs.google.com/spreadsheets/d/117ukLjXiz8EfMjP-q9Aiu5XepQ39XK1W4DTMsE87llw/edit?usp=sharing) in columns:
* Force
* Force URL
* Neighbourhood
* Neighbourhood URL
* Neighbourhood email

Let's add these to the `InfoWindow` where they are available (see [`maptools.js:124`](https://github.com/PoliceRewired/cvth-groups-map/blob/master/js/maptools.js#L124)).

**Suggested UX:**

* If Force or Neighbourhood are available, display a heading "Safety" - then:
* Force -> if available, display a label with: "Your local force:" and the value
* Force URL -> if available, wrap the force label with a link to the URL
* Neighbourhood -> if available, display a label with: "Your neighbourhood policing team: " and the value
* Neighbourhood URL -> if available, wrap the neighbourhood label with a link to the URL
* Neighbourhood email -> if available, add an extra entry with a `mailto:` link for the email, and the email address itself visible to the user

NB. The columns are mapped to properties on the `community` object. I've not yet checked what happens to spaces in column names.

**Comment by JPixDev** [comment]
I'm currently working on this issue and will do a pull request when it's ready. Thanks for sending me the details @lewis-policecoder

**Comment by ghost** [comment]
Resolved with thanks @JPixDev
